#! /usr/bin/env python3



def main():
    number = input("Input a number\n")
    switch = number[0].upper()
    number = number[1:]
    if ( switch == 'F' ):
        x = FibNumber(int(number))
        print(x)
    elif ( switch == 'D' ):
        x = HexNumber(int(number))
        print(x)
    else:
        x = RomanNum(number)
        print(x)
    return

def FibNumber(number):
    number = number - 2
    x = 1
    y = 1
    if (number > 0):
        for z in range(0,number):
            if ( x > y ) :
                y = y + x
            else:
                x = x + y
    if ( x > y ):
        return x
    return y

def HexNumber(number):
    return hex(number)


def RomanNum(number):
    total = 0;
    for each in number.upper():
        print(total)
        if ( each == 'M' ):
            if( total % 1000 != 0 ):
                total -= ((total % 1000) * 2)
            total += 1000
        elif ( each == 'D' ):
            if ( total % 500 != 0 ):
                total -= ((total % 500) * 2)
            total += 500
        elif ( each == 'C' ):
            if ( total % 100 != 0):
                total -= ((total % 100) * 2)
            total += 100
        elif ( each == 'L' ):
            if ( total % 50 != 0):
                total -= ((total % 50) * 2)
            total += 50
        elif ( each == 'X' ):
            if ( total % 10 != 0):
                total -= ((total % 10) * 2)
            total += 10
        elif ( each == 'V' ):
            if ( total % 5 != 0):
                total -= ((total % 5) * 2)
            total += 5
        elif ( each == 'I' ):
            total += 1
        else:
            total = ("Not a valid roman numberal.")
            return total
    return total

if __name__ == '__main__':
    main()
