#! /usr/bin/env python3

import sys #For argv[0] on usage statement
import os  #For UID
import socket #Most likely for estting up socket.  Not sure

def main():
    try:
        UDP_IP = "127.0.0.1"
        UDP_PORT1 = int(os.getuid())
        UDP_PORT2 = int(os.getuid()) + 1000
        UDP_PORT3 = int(os.getuid()) + 2000

        sock1 = socket.socket(socket.AF_INET, # Internet
                socket.SOCK_DGRAM) # UDP
        sock1.bind((UDP_IP, UDP_PORT1))

        sock2 = socket.socket(socket.AF_INET, # Internet
                socket.SOCK_DGRAM) # UDP
        sock2.bind((UDP_IP, UDP_PORT2))

        sock3 = socket.socket(socket.AF_INET, # Internet
                socket.SOCK_DGRAM) # UDP
        sock3.bind((UDP_IP, UDP_PORT3))
                                
        while True:
            print("Running:  Ctrl + C to quit.")
            number, addr = sock1.recvfrom(1024) # buffer size is 1024 bytes
            print("received message on Sock1:", number)
            number, addr = sock2.recvfrom(1024)
            print("Received message on Sock2:", number)
            number, addr = sock3.recvfrom(1024)
            print("Received message on Sock3:", number)

            switch = number[0].upper()
            number = number[1:]
            if ( switch == 'F' ):
                x = FibNumber(int(number))
                print(x)
            elif ( switch == 'D' ):
                x = HexNumber(int(number))
                print(x)
            elif ( switch == 'R' ):
                x = RomanNum(number)
                print(x)
            else:
                print("Please precede your number with F for Fibonacci,",\
                        "D for Decimal to Hex, or R for Roman Numerals")
    except IndexError:
        print("Usage:",sys.argv[0]," <(F/D/R)#####>")
    except KeyboardInterrupt:
        return 0

def FibNumber(number):
    number = number - 2
    x = 1
    y = 1
    if (number > 0):
        for z in range(0,number):
            if ( x > y ) :
                y = y + x
            else:
                x = x + y
    if ( x > y ):
        return hex(x)
    return hex(y)

def HexNumber(number):
    return hex(number)


def RomanNum(number):
    total = 0;
    for each in number.upper():
        if ( each == 'M' ):
            if( total % 1000 != 0 ):
                total -= ((total % 1000) * 2)
            total += 1000
        elif ( each == 'D' ):
            if ( total % 500 != 0 ):
                total -= ((total % 500) * 2)
            total += 500
        elif ( each == 'C' ):
            if ( total % 100 != 0):
                total -= ((total % 100) * 2)
            total += 100
        elif ( each == 'L' ):
            if ( total % 50 != 0):
                total -= ((total % 50) * 2)
            total += 50
        elif ( each == 'X' ):
            if ( total % 10 != 0):
                total -= ((total % 10) * 2)
            total += 10
        elif ( each == 'V' ):
            if ( total % 5 != 0):
                total -= ((total % 5) * 2)
            total += 5
        elif ( each == 'I' ):
            total += 1
        else:
            total = ("Not a valid roman numberal.")
            return total
    if (total < 0):
        return "Please order your roman numerals correctly,\
                with the largest value first."
    return hex(total)

if __name__ == '__main__':
    main()
